name: CI - Build and Test QNBScoring

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: windows-2025


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  

      - name: Display .NET SDK version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution without LDAP
        run: dotnet build --no-restore --configuration Release /p:DefineConstants="DISABLE_LDAP"


      - name: Run unit tests
        run: dotnet test --no-build --configuration CI --logger trx