name: CI - Build and Test QNBScoring

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.0'  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution with DISABLE_LDAP symbol
        run: dotnet build --no-restore --configuration CI

      - name: Run unit tests
        run: dotnet test --no-build --configuration CI --logger trx
