name: CI - Build, Test, and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Display .NET SDK version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution without LDAP
        run: dotnet build --no-restore --configuration Release /p:DefineConstants="DISABLE_LDAP"

      - name: Install Coverlet
        run: dotnet add QNBScoring.Tests package coverlet.collector

      - name: Run unit tests with coverage
        run: dotnet test --no-build --configuration Release --logger trx --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate HTML coverage report
        run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Html

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: coverage-report
          path: coverage-report